Controllers/QLNhanSuChinhThucController.cs
using AutoMapper;
using CommonHelper.String;
using CommonHelper.Upload;
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Hinet.Model.IdentityEntities;
using Hinet.Model.Entities;
using Hinet.Service.Common;
using Hinet.Service.Constant;
using Hinet.Web.Areas.QLNhanSuChinhThucArea.Models;
using Hinet.Web.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using Hinet.Web.Filters;
using Hinet.Service.QLNhanSuChinhThucService;
using Hinet.Service.QLNhanSuChinhThucService.Dto;
using CommonHelper.Excel;
using CommonHelper.ObjectExtention;
using Hinet.Web.Common;
using System.IO;
using System.Web.Configuration;
using CommonHelper;
using Hinet.Service.DM_DulieuDanhmucService;



namespace Hinet.Web.Areas.QLNhanSuChinhThucArea.Controllers
{
    public class QLNhanSuChinhThucController : BaseController
    {
        private readonly ILog _Ilog;
        private readonly IMapper _mapper;
        public const string permissionIndex = "QLNhanSuChinhThuc_index";
        public const string permissionCreate = "QLNhanSuChinhThuc_create";
        public const string permissionEdit = "QLNhanSuChinhThuc_edit";
        public const string permissionDelete = "QLNhanSuChinhThuc_delete";
        public const string permissionImport = "QLNhanSuChinhThuc_import";
        public const string permissionExport = "QLNhanSuChinhThuc_export";
        public const string searchKey = "QLNhanSuChinhThucPageSearchModel";
        private readonly IQLNhanSuChinhThucService _QLNhanSuChinhThucService;
        private readonly IDM_DulieuDanhmucService _dM_DulieuDanhmucService;


        public QLNhanSuChinhThucController(IQLNhanSuChinhThucService QLNhanSuChinhThucService, ILog Ilog,

        IDM_DulieuDanhmucService dM_DulieuDanhmucService,
            IMapper mapper
            )
        {
            _QLNhanSuChinhThucService = QLNhanSuChinhThucService;
            _Ilog = Ilog;
            _mapper = mapper;
            _dM_DulieuDanhmucService = dM_DulieuDanhmucService;

        }
        // GET: QLNhanSuChinhThucArea/QLNhanSuChinhThuc
        //[PermissionAccess(Code = permissionIndex)]
        public ActionResult Index()
        {
            var listData = _QLNhanSuChinhThucService.GetDaTaByPage(null);
            SessionManager.SetValue(searchKey, null);
            return View(listData);
        }

        [HttpPost]
        public JsonResult getData(int indexPage, string sortQuery, int pageSize)
        {
            var searchModel = SessionManager.GetValue(searchKey) as QLNhanSuChinhThucSearchDto;
            if (!string.IsNullOrEmpty(sortQuery))
            {
                if (searchModel == null)
                {
                    searchModel = new QLNhanSuChinhThucSearchDto();
                }
                searchModel.sortQuery = sortQuery;
                if (pageSize > 0)
                {
                    searchModel.pageSize = pageSize;
                }
                SessionManager.SetValue(searchKey, searchModel);
            }
            var data = _QLNhanSuChinhThucService.GetDaTaByPage(searchModel, indexPage, pageSize);
            return Json(data);
        }
        //[PermissionAccess(Code = permissionCreate)]
        public PartialViewResult Create()
        {
            var myModel = new CreateVM();

            return PartialView("_CreatePartial", myModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Create(CreateVM model)
        {
            var result = new JsonResultBO(true, "Thêm thông tin nhân viên thành công");
            try
            {
                if (ModelState.IsValid)
                {
                    var EntityModel = _mapper.Map<QLNhanSuChinhThuc>(model);

                    _QLNhanSuChinhThucService.Create(EntityModel);
                }

            }
            catch (Exception ex)
            {
                result.MessageFail(ex.Message);
                _Ilog.Error("Lỗi tạo mới Quản lý thông tin ứng viên", ex);
            }
            return Json(result);
        }

        //[PermissionAccess(Code = permissionEdit)]
        public PartialViewResult Edit(long id)
        {
            var myModel = new EditVM();

            var obj = _QLNhanSuChinhThucService.GetById(id);
            if (obj == null)
            {
                throw new HttpException(404, "Không tìm thấy thông tin");
            }

            myModel = _mapper.Map(obj, myModel);
            return PartialView("_EditPartial", myModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public JsonResult Edit(EditVM model)
        {
            var result = new JsonResultBO(true);
            try
            {
                if (ModelState.IsValid)
                {

                    var obj = _QLNhanSuChinhThucService.GetById(model.Id);
                    if (obj == null)
                    {
                        throw new Exception("Không tìm thấy thông tin");
                    }

                    obj = _mapper.Map(model, obj);

                    _QLNhanSuChinhThucService.Update(obj);

                }
            }
            catch (Exception ex)
            {
                result.Status = false;
                result.Message = "Không cập nhật được";
                _Ilog.Error("Lỗi cập nhật thông tin Quản lý thông tin ứng viên", ex);
            }
            return Json(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult searchData(QLNhanSuChinhThucSearchDto form)
        {
            var searchModel = SessionManager.GetValue(searchKey) as QLNhanSuChinhThucSearchDto;

            if (searchModel == null)
            {
                searchModel = new QLNhanSuChinhThucSearchDto();
                searchModel.pageSize = 20;
            }
            /*
            searchModel.HoTenFilter = form.HoTenFilter;
            searchModel.ViTriUngTuyenFilter = form.ViTriUngTuyenFilter;
            searchModel.EmailFilter = form.EmailFilter;
            searchModel.SoDienThoaiFilter = form.SoDienThoaiFilter;
            searchModel.TruongDaiHocFilter = form.TruongDaiHocFilter;
            searchModel.CongTyCuFilter = form.CongTyCuFilter;
            searchModel.TrangThaiGoiDienFilter = form.TrangThaiGoiDienFilter;
            searchModel.TrangThaiGuiEmailFilter = form.TrangThaiGuiEmailFilter;
            */

            SessionManager.SetValue((searchKey), searchModel);

            var data = _QLNhanSuChinhThucService.GetDaTaByPage(searchModel, 1, searchModel.pageSize);
            return Json(data);
        }

        //[PermissionAccess(Code = permissionDelete)]
        [HttpPost]
        public JsonResult Delete(long id)
        {
            var result = new JsonResultBO(true, "Xóa Quản lý thông tin ứng viên thành công");
            try
            {
                var user = _QLNhanSuChinhThucService.GetById(id);
                if (user == null)
                {
                    throw new Exception("Không tìm thấy thông tin để xóa");
                }
                _QLNhanSuChinhThucService.Delete(user);
            }
            catch (Exception ex)
            {
                result.MessageFail("Không thực hiện được");
                _Ilog.Error("Lỗi khi xóa tài khoản id=" + id, ex);
            }
            return Json(result);
        }


        public ActionResult Detail(long id)
        {
            var model = new DetailVM();
            model.objInfo = _QLNhanSuChinhThucService.GetDtoById(id);
            return View(model);
        }
        //[PermissionAccess(Code = permissionExport)]
        //[PermissionAccess(Code = permissionImport)]
        public FileResult ExportExcel()
        {
            var searchModel = SessionManager.GetValue(searchKey) as QLNhanSuChinhThucSearchDto;
            var data = _QLNhanSuChinhThucService.GetDaTaByPage(searchModel).ListItem;
            var dataExport = _mapper.Map<List<QLNhanSuChinhThucExportDto>>(data);
            var fileExcel = ExportExcelV2Helper.Export<QLNhanSuChinhThucExportDto>(dataExport);
            return File(fileExcel, "application/octet-stream", "QLNhanSuChinhThuc.xlsx");
        }

        //[PermissionAccess(Code = permissionImport)]
        //[PermissionAccess(Code = permissionImport)]
        public ActionResult Import()
        {
            var model = new ImportVM();
            model.PathTemplate = Path.Combine(@"/Uploads", WebConfigurationManager.AppSettings["IMPORT_QLNhanSuChinhThuc"]);

            return View(model);
        }

        [HttpPost]
        public ActionResult CheckImport(FormCollection collection, HttpPostedFileBase fileImport)
        {
            JsonResultImportBO<QLNhanSuChinhThucImportDto> result = new JsonResultImportBO<QLNhanSuChinhThucImportDto>(true);
            //Kiểm tra file có tồn tại k?
            if (fileImport == null)
            {
                result.Status = false;
                result.Message = "Không có file đọc dữ liệu";
                return View(result);
            }

            //Lưu file upload để đọc
            var saveFileResult = UploadProvider.SaveFile(fileImport, null, ".xls,.xlsx", null, "TempImportFile", HostingEnvironment.MapPath("/Uploads"));
            if (!saveFileResult.status)
            {
                result.Status = false;
                result.Message = saveFileResult.message;
                return View(result);
            }
            else
            {

                #region Config để import dữ liệu
                var importHelper = new ImportExcelHelper<QLNhanSuChinhThucImportDto>();
                importHelper.PathTemplate = saveFileResult.fullPath;
                //importHelper.StartCol = 2;
                importHelper.StartRow = collection["ROWSTART"].ToIntOrZero();

Views/QLNhanSuChinhThuc/Import.cshtml
@using Hinet.Web.Areas.QLNhanSuChinhThucArea.Models;
@model ImportVM
    @{
        ViewBag.Title = "Nhập danh mục từ file Excel";
        Layout = "~/Views/Shared/_LayoutAce.cshtml";
        ViewBag.ModuleName = "Quản lý Quản lý thông tin ứng viên";
        ViewBag.PageName = "Nhập dữ liệu Excel";
    }
    <style>
        .no-padding .dataTables_wrapper table, .no-padding > table {
            border: 1px solid #ddd !important;
        }

        .infoTable tr td {
            padding: 5px;
        }

        .infoTable tr th {
            padding: 5px;
            text-align: center;
        }

        .tableinfoData {
            width: 100%;
        }

            .tableinfoData tr td {
                padding: 5px;
            }
    </style>
    @section ActionBarRight{

    }

    <div class="row nomargin" style="margin-top:10px;">

        @*<div class="header">Import Dữ liệu</div>*@
        @using (Html.BeginForm("CheckImport", "QLNhanSuChinhThuc", new { @area = "QLNhanSuChinhThucArea" }, FormMethod.Post, new { id = "formupload", @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-inline">
                <div class="col-sm-6">
                    <table class="tableinfoData">
                        <tr>
                            <td>
                                <label class="control-label ">Tệp nhập dữ liệu<span style="color:red;">*</span></label>
                            </td>
                            <td>
                                <div class="form-group">
                                    <input type="file" name="fileImport" class="form-control Valid IsRequire" />
                                    <div class="note-error">
                                        <span class="error mes-note-error"></span>
                                    </div>
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <td><label class="control-label">Mẫu file Excel</label></td>
                            <td><a href="@Model.PathTemplate" download class=" btn btn-success btn-sm"><i class="fa fa-download"></i> Tải xuống</a></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>

                                <button type="button" class="btn btn-primary" onclick="uploadFile()">Nhập dữ liệu</button>

                            </td>
                        </tr>
                    </table>

                </div>
                <div class="row nomargin form-horizontal">
                    <table class="infoTable table-bordered">
                        <caption class="center Bold">Cấu hình cột lấy thông tin</caption>
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Tên trường thông tin</th>
                                <th>Cấu hình</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Dòng bắt đầu đọc</td>
                                <td><input type="number" data-min="0" class="form-control required validateNumber" name="ROWSTART" value="2" /></td>
                            </tr>

<tr><td>2</td><td>Vị trí ứng tuyển</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="ViTriUngTuyen" value="1" /></td></tr>
<tr><td>3</td><td>Trạng thái phản hồi</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="TrangThaiPhanHoi" value="2" /></td></tr>
<tr><td>4</td><td>Trạng thái kết quả</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="TrangThaiKetQua" value="3" /></td></tr>
<tr><td>5</td><td>Trạng thái xử lý</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="TrangThai" value="4" /></td></tr>
<tr><td>6</td><td>Họ Tên</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="HoTen" value="5" /></td></tr>
<tr><td>7</td><td>Email</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="Email" value="6" /></td></tr>
<tr><td>8</td><td>Số điện thoại</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="SoDienThoai" value="7" /></td></tr>
<tr><td>9</td><td>Trường Đại Học</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="TruongDaiHoc" value="8" /></td></tr>
<tr><td>10</td><td>Công ty cũ</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="CongTyCu" value="9" /></td></tr>
<tr><td>11</td><td>NgaySinh</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="NgaySinh" value="10" /></td></tr>
<tr><td>12</td><td>Nội dung phản hồi</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="NoiDungPhanHoi" value="11" /></td></tr>
<tr><td>13</td><td>Ghi chú kết quả</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="GhiChuKetQua" value="12" /></td></tr>
<tr><td>14</td><td>Ghi chú</td><td><input type="number" data-min="0" class="form-control required validateNumber" name="GhiChu" value="13" /></td></tr>

                            

                        </tbody>

                    </table>
                </div>

            </div>
        }
    </div>


    @section scripts{
        <script src="~/Scripts/ValidateHoanVu.js"></script>
        <script>
            $(".checkBoxControl").click(function () {
                var tbl = $(this).parents("table").first();
                if ($(this).prop("checked")) {
                    tbl.find("input:checkbox.global_checkbox:unchecked").each(function () {
                        $(this).prop("checked", true);
                    })
                } else {
                    tbl.find("input:checkbox.global_checkbox:checked").each(function () {
                        $(this).prop("checked", false);
                    })
                }
            })


            function uploadFile() {
                $("#block-dung").css("display", "none");
                $("#block-sai").css("display", "none");
                var valid = checkForm("formupload");
                if (valid) {
                    $("#formupload").submit();
                } else {
                    NotiError("Vui lòng kiểm tra lại thông tin");
                }
                return false;

            }

        </script>
    }

Views/QLNhanSuChinhThuc/_CreatePartial.cshtml
@using Hinet.Model.IdentityEntities
@using Hinet.Model.Entities
@using Hinet.Web.Areas.QLNhanSuChinhThucArea.Models
@model CreateVM
@{

}
<style>
    .row .form-group{
        margin: 5px;
    }
</style>
<div class="modal-dialog modal-lg">
    @using (Ajax.BeginForm("Create", "QLNhanSuChinhThuc", new { @area = "QLNhanSuChinhThucArea" }, new AjaxOptions()
    {
        HttpMethod = "POST",
        OnFailure = "AjaxFormError",
        OnSuccess = "AjaxFormSuccess",
    }, new { id = "createQLNhanSuChinhThucForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        //HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Tạo mới thông tin ứng viên</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="form-horizontal row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Họ Tên <span class="red">*</span></label>
                            @Html.TextBoxFor(m => m.HoTen, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.HoTen, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Số điện thoại <span class="red">*</span></label>
                            @Html.TextBoxFor(m => m.SoDienThoai, new { @class = "form-control", type = "number" })
                            @Html.ValidationMessageFor(m => m.SoDienThoai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Ngày sinh</label>
                            <input type="text" class="flatpickr-input flatpickr form-control" data-provider="flatpickr" data-date-format="d/M/Y" />
                            @*@Html.Pickr(m => m.NgaySinh, "data-provider=flatpickr", "data-date-format=d M, Y")*@
                            @Html.ValidationMessageFor(m => m.NgaySinh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Địa chỉ Email <span class="red">*</span></label>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <label>Quê quán:</label>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Tỉnh<span class="red">*</span></label>
                            @Html.TextBoxFor(m => m.QueQuanTinh, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.QueQuanTinh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Huyện<span class="red">*</span></label>
                            @Html.TextBoxFor(m => m.QueQuanHuyen, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.QueQuanHuyen, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Xã<span class="red">*</span></label>
                            @Html.TextAreaFor(m => m.QueQuanXa, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.QueQuanXa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Địa chỉ</label>
                            @Html.TextAreaFor(m => m.QueQuanDiaChi, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.QueQuanDiaChi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <label>Địa chỉ hiện tại:</label>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Tỉnh</label>
                            @Html.TextAreaFor(m => m.DiaChiHienTaiTinh, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.DiaChiHienTaiTinh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Huyện</label>
                            @Html.TextAreaFor(m => m.DiaChiHienTaiHuyen, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.DiaChiHienTaiHuyen, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Xã</label>
                            @Html.TextAreaFor(m => m.DiaChiHienTaiXa, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.DiaChiHienTaiXa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Địa chỉ</label>
                            @Html.TextAreaFor(m => m.DiaChiHienTaiDiaChi, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.DiaChiHienTaiDiaChi, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Phòng ban</label>
                            @Html.TextAreaFor(m => m.PhongBan, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.PhongBan, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Vị trí</label>
                            @Html.TextAreaFor(m => m.ViTri, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.ViTri, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Trình độ đào tạo</label>
                            @Html.TextAreaFor(m => m.TrinhDoDaoTao, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.TrinhDoDaoTao, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Ngày vào công ty</label>
                            @Html.TextAreaFor(m => m.NgayVaoCongTy, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.NgayVaoCongTy, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Trạng thái</label>
                            @Html.TextAreaFor(m => m.TrangThai, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Tài liệu đính kèm</label>
                            @Html.TextAreaFor(m => m.TaiLieuDinhKem, 4, 3, new { @class = "form-control resize-vertical" })
                            @Html.ValidationMessageFor(m => m.TaiLieuDinhKem, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer center">
                <button type="submit" class="btn btn-primary">Hoàn thành</button>

                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Đóng</button>
            </div>
        </div>
    }
</div>

<script>

</script>
@Scripts.Render("~/bundles/jqueryval")

Views/QLNhanSuChinhThuc/_SearchPartial.cshtml
<style>
    .fix_btnEx {
        margin: 0 6px !important;
    }
    .row-block {
        margin: 8px 0;
    }
</style>
<div id="collapseDiv" class="panel-collapse collapse" aria-expanded="false" role="tabpanel">
    <div class="well SearchBox">

        @using (Ajax.BeginForm("searchData", "QLNhanSuChinhThuc", new { Area = "QLNhanSuChinhThucArea" },
            new AjaxOptions()
            {
                HttpMethod = "POST",
                OnFailure = "AjaxFormError",
                OnSuccess = "AjaxSearchSuccess",
            }, new { }))
        {
            @Html.AntiForgeryToken()
        <div class="row row-block">
            <div class="col-md-6 row-block">
                <div class="col-md-4 txt-label">Họ Tên</div>
                <div class="col-md-8">
                    <input class="form-control width100" type="text" name="HoTenFilter" />
                </div>
            </div>

            <div class="col-md-6 row-block">
                <div class="col-md-4 txt-label">Số điện thoại</div>
                <div class="col-md-8">
                    <input type="number" class="form-control width100" name="SoDienThoaiFilter" />
                </div>
            </div>

            <div class="col-md-6 row-block">
                <div class="col-md-4 txt-label">Email</div>
                <div class="col-md-8">
                    <input class="form-control width100" type="text" name="EmailFilter" />
                </div>
            </div>


            <div class="col-md-6 row-block">
                <div class="col-md-4 txt-label">Phòng ban</div>
                <div class="col-md-8">
                    <input class="form-control width100" type="text" name="PhongBanFilter" />
                </div>
            </div>

            <div class="col-md-6 row-block">
                <div class="col-md-4 txt-label">Vị trí</div>
                <div class="col-md-8">
                    <input class="form-control width100" type="text" name="ViTriFilter" />
                </div>
            </div>

            <div class="col-md-6 row-block">
                <div class="col-md-4 txt-label">Trình độ đào tạo</div>
                <div class="col-md-8">
                    <input class="form-control width100" type="text" name="TrinhDoDaoTaoFilter" />
                </div>
            </div>

            <div class="col-md-6 row-block">
                <div class="col-md-4 txt-label">Trạng thái</div>
                <div class="col-md-8">
                    <input class="form-control width100" type="text" name="TrangThaiFilter" />
                </div>
            </div>


            <div class="col-md-12 center" style=" margin-top:20px;">
                <button id="btnSearch" type="submit" class="btn btn-labeled btn-primary btn-sm fix_btnFind">
                    <span class="btn-label p-0">
                        <i class="ri-search-line "></i>
                    </span>
                    Tìm kiếm
                </button>
                <a href="/QLNhanSuChinhThucArea/QLNhanSuChinhThuc/ExportExcel" class="btn btn-labeled btn-success btn-sm fix_btnEx"><span class='btn-label p-0'><i class='ri-download-2-line'></i></span> Xuất Excel</a>
                <a aria-expanded="false" href="#collapseDiv" data-toggle="collapse" role="button" class="btn btn-labeled btn-danger btn-sm fix_btnClose">
                    <span class="btn-label p-0"><i class="ri-close-line"></i></span>
                    Đóng
                </a>
            </div>
        </div>

        }
    </div>
</div>